version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      actions:
        patterns: ["*"]
  - package-ecosystem: npm
    directory: /integrations/github-action
    schedule:
      interval: monthly
    groups:
      npm:
        patterns: ["*"]
  - package-ecosystem: npm
    directory: /integrations/benchmark
    schedule:
      interval: monthly
    groups:
      npm:
        patterns: ["*"]
  - package-ecosystem: npm
    directory: /integrations/nextjs-starter
    schedule:
      interval: monthly
    groups:
      npm:
        patterns: ["*"]
  - package-ecosystem: npm
    directory: /integrations/storybook
    schedule:
      interval: monthly
    groups:
      npm:
        patterns: ["*"]
